# Generated by Django 3.1.12 on 2021-09-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210824_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
