# Generated by Django 3.1.12 on 2021-09-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210906_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ordered'), (3, 'Delivering'), (2, 'Paid'), (4, 'Successful'), (0, 'Canceled')], default=1),
        ),
    ]
