# Generated by Django 3.1.12 on 2021-08-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('sold', models.IntegerField(default=0)),
                ('size', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
